-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 10:21:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_delivery` DEFAULT CHARACTER SET utf8 ;
USE `food_delivery` ;

-- -----------------------------------------------------
-- Table `food_delivery`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Kayttajatunnus` VARCHAR(45) NULL,
  `Salasana` VARCHAR(45) NULL,
  `Osoite` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`Owner` (
  `idOwner` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Kayttajatunnus` VARCHAR(45) NULL,
  `Salasana` VARCHAR(45) NULL,
  `Osoite` VARCHAR(45) NULL,
  PRIMARY KEY (`idOwner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`Restaurants` (
  `idRestaurants` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Osoite` VARCHAR(45) NULL,
  PRIMARY KEY (`idRestaurants`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`Owner_Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`Owner_Restaurants` (
  `Owner_idOwner` INT NOT NULL,
  `Restaurants_idRestaurants` INT NOT NULL,
  PRIMARY KEY (`Owner_idOwner`, `Restaurants_idRestaurants`),
  INDEX `fk_Owner_Restaurants_Owner_idx` (`Owner_idOwner` ASC) VISIBLE,
  INDEX `fk_Owner_Restaurants_Restaurants1_idx` (`Restaurants_idRestaurants` ASC) VISIBLE,
  CONSTRAINT `fk_Owner_Restaurants_Owner`
    FOREIGN KEY (`Owner_idOwner`)
    REFERENCES `food_delivery`.`Owner` (`idOwner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Owner_Restaurants_Restaurants1`
    FOREIGN KEY (`Restaurants_idRestaurants`)
    REFERENCES `food_delivery`.`Restaurants` (`idRestaurants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`Orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Customer1_idx` (`Customer_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `food_delivery`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
